### ISSUE TITLE
Intersections not found

### ISSUE THREAD

**Issue by asos-tomp** [crazytoucan/math2d#23]
Apologies for no fiddle/pen on this, I couldn't find math2d on a CDN nor a packaged version for use with unpkg

Consider the following code:
```
import { polygonIntersectRay, rayLookAt } from "math2d";

const getBoundingPolygon = ({ width, height }) => {
  const topLeft = [0, 0];
  const topRight = [width, 0]
  const bottomLeft = [0, height];
  const bottomRight = [width, height];
  return [
    ...topLeft,
    ...topRight,
    ...bottomRight,
    ...bottomLeft
  ];
};

const unitSquarePolygon = getBoundingPolygon({ width: 1, height: 1 });
const centreVec = { x: 0.5, y: 0.5 };
const rayFromCentrePositiveXDirection = rayLookAt(centreVec, { x: 0.6, y: 0.5 });
const rayFromCenterNegativeXDirection = rayLookAt(centreVec, { x: 0.4, y: 0.5 });
```
The former ray is deemed to have intersected correctly:
```
polygonIntersectRay(unitSquarePolygon, rayFromCentrePositiveXDirection);
```
> PointIntersectionResult
> exists: true
> t0: 1.5
> t1: 0.5
> x: 1
> y: 0.5

...whereas the latter is not deemed to have intersected:
```
polygonIntersectRay(unitSquarePolygon, rayFromCenterNegativeXDirection);
```
> []

Is there something obvious I'm doing wrong?

**Comment by crazytoucan** [comment]
Hey @asos-tomp , thanks for the bug report and I really do apologize for the issues you hit when you were trying out the library. I know you have probably moved onto other solutions in the meantime, but do let me know if you come back and see anything else that needs to be addressed.
